example.html
packages/browser-wallet-api/src/wallet-api.ts
packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
packages/browser-wallet/src/popup/pages/SignMessage/i18n/da.ts
packages/browser-wallet/src/popup/pages/SignMessage/i18n/en.ts
packages/browser-wallet/src/popup/shell/Routes.tsx

Allow signing a message.
Implements the flow for signing a message, and returning the signature.

Allow signing messages

---

packages/browser-wallet-api-types/CHANGELOG.md
packages/browser-wallet-api-types/package.json

update api-types version and add changelog

Add changelog to api-types and bump version

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Bump version of app prior to release.

bumped to 0.2.0

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/page-layouts/MainLayout/Header/Header.scss
packages/browser-wallet/src/popup/page-layouts/MainLayout/Header/Header.tsx
packages/browser-wallet/src/popup/pages/Account/Account.scss
packages/browser-wallet/src/popup/pages/Account/Account.tsx
packages/browser-wallet/src/popup/pages/Account/DisplayAddress/DisplayAddress.scss
packages/browser-wallet/src/popup/pages/Account/DisplayAddress/DisplayAddress.tsx
packages/browser-wallet/src/popup/pages/Account/DisplayAddress/index.ts
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/shared/MenuButton/MenuButton.scss
packages/browser-wallet/src/popup/shared/MenuButton/MenuButton.tsx
packages/browser-wallet/src/popup/shared/MenuButton/index.ts
packages/browser-wallet/src/popup/styles/_components.scss
packages/browser-wallet/src/popup/styles/elements/_typography.scss
yarn.lock

Adds the display of the account address as text and QR in the "receive ccd" section.
Added the DisplayAddress component.

Add display of account address

---

packages/browser-wallet/src/popup/shared/Button/Button.scss
packages/browser-wallet/src/popup/shared/Carousel/Carousel.scss
packages/browser-wallet/src/popup/shared/Carousel/Carousel.stories.tsx
packages/browser-wallet/src/popup/shared/Carousel/Carousel.tsx
packages/browser-wallet/src/popup/shared/Carousel/index.ts
packages/browser-wallet/src/popup/styles/_components.scss
packages/browser-wallet/src/popup/styles/config/_variables.scss

Adds a carousel component to be used for displaying single or multiple pages with information.
- Add carousel component

Carousel component

---

packages/browser-wallet/src/popup/page-layouts/MainLayout/Header/Header.tsx
packages/browser-wallet/src/popup/pages/Setup/Setup.tsx
packages/browser-wallet/src/popup/shell/Root.tsx
packages/browser-wallet/src/popup/shell/Routes.tsx

Remove redirection on empty path, so that prompt won't get redirected to account page.
Now initial entry in history is account page.

Start on account page instead of redirecting to it

---

.eslintrc.js
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/page-layouts/MainLayout/AccountList/AccountList.tsx
packages/browser-wallet/src/popup/pages/Account/AccountDetails/AccountDetails.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/util.ts
packages/browser-wallet/src/popup/shared/account-info-emitter.ts
packages/browser-wallet/src/popup/store/settings.ts
yarn.lock

Get the account balances periodically from the JSON-RPC server to show in the UI.
- Added an event emitter where one can subscribe to getting the account info periodically. It also allows for listening to changes in the balance only.
- Errors are not handled as we have yet to define how this is to be shown in the UI. TODO's have been left in their place.
- The JSON-RPC url in the state is made mandatory, i.e. it can no longer be undefined.

Account balance

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Get ready for releasing a new version.

Update CHANGELOG and bump version

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/NetworkSettings/NetworkSettings.tsx

- Update changelog
- Bump version
- add remote JsonRpcUrl for stagenet

Update changelog + bump version + add remote jsonRpcUrl for stagenet

---

packages/browser-wallet/src/popup/shared/Form/InlineInput/InlineInput.tsx
packages/browser-wallet/src/popup/shared/Form/Input/Input.tsx
packages/browser-wallet/src/popup/shared/Form/TextArea/TextArea.tsx

Remove spellcheck and autocomplete from input fields.
- Disabled spellcheck and autocomplete in our base input components.

Disable spellcheck and autocomplete

---

packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceEnd.tsx
packages/browser-wallet/src/popup/pages/IdentityIssuance/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdentityIssuance/i18n/en.ts

Rename continue button to done at end of issuance

---

packages/browser-wallet/src/background/identity-issuance.ts
packages/browser-wallet/src/popup/page-layouts/MainLayout/AccountList/AccountList.tsx
packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
packages/browser-wallet/src/popup/shared/Form/common/utils.tsx
packages/browser-wallet/src/popup/state/index.ts
packages/browser-wallet/src/popup/store/account.ts
packages/browser-wallet/src/popup/store/utils.ts
packages/browser-wallet/src/shared/storage/access.ts
packages/browser-wallet/src/shared/storage/types.ts

Fix duplicate account issue + crashing when creating account + error appearing in log in setup.
+ Fixed `makeUncontrolled` valid prop.
+ AccountList no longer handles account infos, this has been pushed to list items.
+ Stop user from starting another credential request.

Block duplicate account issue + fix other bugs

---

packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx

Fix error in log.
- Made keys unique

Add provider index to key

---

packages/browser-wallet/src/popup/pages/Identity/Identity.tsx

Fix "Recovered IDs have wrong icon".
Update IDP icon when selected identity changes.

Update identity provider icon when changing identity

---

packages/browser-wallet/src/background/identity-issuance.ts
packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceStart.tsx

Ensure errors during identity issuance is caught and not propagated into the log.
Catch errors from fetch in background script, and when getting IDP's in identityIssuanceStart.

Catch errors during identity issuance

---

packages/browser-wallet/src/popup/pages/Setup/GenerateSeedPhrase.tsx
packages/browser-wallet/src/popup/pages/Setup/RecoveryPhrase.tsx
packages/browser-wallet/src/popup/shared/Form/TextArea/TextArea.tsx

Disable copy and paste of seed phrase during setup.

Prevent copy and paste of seed phrase in setup

---

packages/browser-wallet/src/background/recovery.ts

Fix background script crashing
Background script no longer imports from popup (probably react specifically)

Ensure background script doesnt import from popup

---

packages/browser-wallet/src/background/identity-issuance.ts
packages/browser-wallet/src/popup/pages/Account/Account.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/pages/Identity/Identity.tsx
packages/browser-wallet/src/popup/pages/Identity/i18n/da.ts
packages/browser-wallet/src/popup/pages/Identity/i18n/en.ts
packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
packages/browser-wallet/src/popup/shell/i18n/locales/en.ts

- Improve views when there are no identities / accounts.
- Fix aborting identity issuance not reset sessionPendingIdentity

Small improvements

---

packages/browser-wallet/src/popup/pages/NetworkSettings/NetworkSettings.tsx
packages/browser-wallet/src/popup/pages/Setup/ChooseNetwork.tsx

Remove stagenet.
- Removed stagenet

Remove stagenet

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Bump version and update changelog.

Bump version to 0.7.0

---

packages/browser-wallet/src/popup/shared/utils/seedPhrase-helpers.ts

Fix useDecryptedSeedPhrase not updating from undefined if deps where loading on first render.

Fix seedphrase staying as undefined

---

packages/browser-wallet/src/popup/pages/Recovery/RecoveryFinish.tsx

Fix recovery showing nothing recovered when only accounts have been recovered. (or if there have been discovered another identity, not showing recovered accounts on existing accounts)
Add missing elements of dependency arrays.

Recovering from BW - account was found

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Bump version to v0.7.2

---

packages/browser-wallet/src/popup/pages/Setup/i18n/en.ts

Fix some typos found during testing.
- Updated translation file.

Fix typos in setup text

---

packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Improve account action button hover texts.
- Updated translation files.

Capitalize account action hover texts

---

examples/piggybank/package.json
examples/wCCD/package.json
packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api/package.json
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
yarn.lock

Update web sdk dependency to 2.0.0

---

packages/browser-wallet/src/background/recovery.ts

use getCredentialId instead of creating a CredentialDeployment in recovery.

Recovery now uses getCredentialId

---

packages/browser-wallet/package.json

Bump version to 0.7.3

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/NetworkSettings/NetworkSettings.tsx

Use correct url for json-rpc
Changed url to the correct one.

Use correct json rpc url for mainnet

---

examples/wCCD/src/utils.ts

Fix linting wCCD example

---

packages/browser-wallet/manifest.json

Remove the unused notifications permission from manifest.

Remove notifications permission

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/ChangePasscode/ChangePasscode.tsx
packages/browser-wallet/src/popup/pages/ChangePasscode/i18n/da.ts
packages/browser-wallet/src/popup/pages/ChangePasscode/i18n/en.ts

Give user feedback when updating the passcode.
- Added a toast to indicate a successful update.

Show toast on successful passcode update

---

examples/wCCD/src/Root.tsx
examples/wCCD/src/constants.ts
examples/wCCD/src/utils.ts
examples/wCCD/src/wCCD.tsx

Disable mainnet connection on wCCD example

Change: disable mainnet connection

---

packages/browser-wallet/src/popup/shared/TokenBalance.tsx

Adds space between token balance and symbol.

added space between balance and symbol

---

packages/browser-wallet/src/popup/pages/Setup/SetupPasscode.tsx

Correctly revalidate password fields when either field changes its value.

Improve password setup validation

---

packages/browser-wallet/src/background/identity-issuance.ts
packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceStart.tsx

Ensure that identity issuance doesn't hang forever.

IdentityIssuance start now expects a response from the background script

---

packages/browser-wallet/src/background/confirmation.ts
packages/browser-wallet/src/popup/pages/Account/Account.scss
packages/browser-wallet/src/popup/pages/Account/Account.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Allow accounts to be rejected instead of endlessly pending + display that.

Allow accounts to be rejected

---

packages/browser-wallet/src/popup/pages/Account/ManageTokens/TokenList.tsx

Ensure search value is present in search field when coming back from details page

---

packages/browser-wallet/src/popup/pages/Account/ManageTokens/ManageTokens.tsx
packages/browser-wallet/src/popup/pages/Account/Tokens/TokenDetails.tsx
packages/browser-wallet/src/popup/pages/Account/Tokens/Tokens.tsx
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionLog.tsx

On account change:
- Route to tokens root for token details
- Route to transaction list for transaction details
- Route to tokens for manage tokens

fall back to a sensible route on account change

---

packages/browser-wallet-api/src/wallet-api.ts
packages/browser-wallet-message-hub/src/util.ts
packages/browser-wallet/src/background/index.ts
packages/browser-wallet/src/background/recovery.ts
packages/browser-wallet/src/background/window-management.ts
packages/browser-wallet/src/popup/shell/Routes.tsx
packages/browser-wallet/src/popup/store/utils.ts
packages/browser-wallet/src/shared/storage/access.ts
packages/browser-wallet/src/shared/storage/types.ts

Ensure that we don't open multiple prompts at the same time.
- Add variable to check if a prompt is already open, reject if it is sat.
- Reworked the type sent between the script.

Reject prompt requests, if there is already a prompt open

---

packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
packages/browser-wallet/src/popup/pages/AddAccount/i18n/en.ts
packages/browser-wallet/src/popup/pages/Identity/i18n/en.ts
packages/browser-wallet/src/popup/pages/IdentityIssuance/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdentityIssuance/i18n/en.ts
packages/browser-wallet/src/popup/pages/Recovery/i18n/da.ts
packages/browser-wallet/src/popup/pages/Setup/RecoverSeedPhrase.tsx
packages/browser-wallet/src/popup/pages/Setup/RecoveryPhrase.tsx
packages/browser-wallet/src/popup/pages/Setup/i18n/da.ts
packages/browser-wallet/src/popup/pages/Setup/i18n/en.ts

Update text based on feedback.

Textual changes

---

packages/browser-wallet/src/background/identity-issuance.ts
packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuance.scss

Handle identity provider sending `error` instead of `code_uri`

Proper handling of Notabene error format 

---

packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
packages/browser-wallet/src/shared/utils/energy-helpers.ts
packages/browser-wallet/src/shared/utils/token-helpers.ts

Fix display of update transactions' amounts in transaction list.

Add green text, when update results in net positive for the sender

---

packages/browser-wallet/src/popup/pages/Account/SendCcd/ConfirmTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/Tokens/Tokens.scss
packages/browser-wallet/src/popup/pages/Account/Tokens/Tokens.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/shared/TokenDetails/TokenDetails.tsx

Add text to explain where to add tokens from, if the selected list for the account contains few or no tokens.

Empty tokens list message

---

packages/browser-wallet/src/popup/pages/Account/SendCcd/ConfirmTokenTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
packages/browser-wallet/src/shared/utils/token-helpers.ts

Block token transfers if simulation fails + improve error message.

Improve handling of bad token transfer

---

packages/browser-wallet/src/popup/pages/Account/ManageTokens/ManageTokens.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/shared/utils/token-helpers.ts

Add proper error when tokenMetadata fails during manage.

improve handling of bad tokenMetadata

---

examples/nft-minting/package.json
examples/nft-minting/src/utils.ts
examples/piggybank/package.json
examples/piggybank/src/Version0.tsx
examples/piggybank/src/utils.ts
examples/wCCD/package.json
packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api-helpers/src/wallet-api-types.ts
packages/browser-wallet-api/package.json
packages/browser-wallet-api/src/util.ts
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/Account/SendCcd/ConfirmSimpleTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/SendCcd/ConfirmTokenTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/SendCcd/ConfirmTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/util.ts
packages/browser-wallet/src/popup/shared/TransactionReceipt/TransactionReceipt.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayGenericPayload.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayInitContract.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplaySimpleTransfer.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayUpdateContract.tsx
packages/browser-wallet/src/popup/shared/utils/transaction-helpers.ts
packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
packages/browser-wallet/src/shared/utils/token-helpers.ts
yarn.lock

Use the new web-sdk version.
Changed names based on web-sdk update.

Update web-sdk to 3.0.0

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Bump version to 0.8.1

---

packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/SendCcd/SendCcd.tsx

Fix react error appearing, when entering the transfer flow.

Fix react error in transfer flow

---

packages/browser-wallet/src/popup/shared/i18n/da.ts
packages/browser-wallet/src/popup/shared/i18n/en.ts

Change amount label for token transfer

---

packages/browser-wallet/src/popup/pages/Setup/SetupPasscode.tsx

Align password validation with general validation style of app

Validate password "on touched"

---

packages/browser-wallet/src/popup/shared/TokenDetails/TokenDetails.tsx
packages/browser-wallet/src/popup/shared/i18n/da.ts
packages/browser-wallet/src/popup/shared/i18n/en.ts

Notify in wallet when a token has been removed.

Remove token notification

---

packages/browser-wallet/src/popup/pages/Account/ManageTokens/TokenList.tsx

Fix token search, so the wallet doesn't crash
Fix token search, so it does not put undefined in the list, if there is no token.
+ fix the incorrect type.

Fix token search, so the wallet doesn't crash

---

packages/browser-wallet/src/popup/pages/Account/ManageTokens/ManageTokens.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Change text on button to look for tokens, to align with mw.

Fix look for token button text

---

packages/browser-wallet/src/popup/pages/Account/SendCcd/DisplayToken.tsx
packages/browser-wallet/src/popup/pages/Account/SendCcd/PickToken.tsx
packages/browser-wallet/src/popup/shared/TokenDetails/TokenDetails.tsx
packages/browser-wallet/src/shared/utils/token-helpers.ts

Correct Incorrect types for token balances floating around.

Fix incorrect type on contract balance

---

packages/browser-wallet/src/background/index.ts

Add network dimension to matomo

---

examples/two-step-transfer/index.html
packages/browser-wallet-api/src/util.ts
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayInitContract.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayUpdateContract.tsx

Bump version and fix errors with external prompts.
Check commits

Bump version + fixes

---

packages/browser-wallet/src/popup/shared/TokenDetails/TokenDetails.tsx

Ensure that after removing a collectible, we go back to the collectible page.

Improve navigation after removing token

---

packages/browser-wallet/src/popup/pages/Account/ManageTokens/TokenList.tsx
packages/browser-wallet/src/popup/pages/IdentityIssuance/i18n/en.ts

Fix incorrect Id appearing on tokens when searching.
Perform more check before searching for tokens

Fix incorrect id on search/searching on non-hex values

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/background/index.ts
packages/browser-wallet/src/popup/constants/routes.ts
packages/browser-wallet/src/popup/constants/urls.ts
packages/browser-wallet/src/popup/page-layouts/MainLayout/MainLayout.tsx
packages/browser-wallet/src/popup/pages/About/About.tsx
packages/browser-wallet/src/popup/pages/Setup/Setup.scss
packages/browser-wallet/src/popup/pages/Setup/Setup.tsx
packages/browser-wallet/src/popup/pages/Setup/i18n/da.ts
packages/browser-wallet/src/popup/pages/Setup/i18n/en.ts
packages/browser-wallet/src/popup/pages/TermsAndConditions/AcceptTerms.tsx
packages/browser-wallet/src/popup/pages/TermsAndConditions/TermsAndConditions.scss
packages/browser-wallet/src/popup/pages/TermsAndConditions/TermsAndConditions.tsx
packages/browser-wallet/src/popup/pages/TermsAndConditions/i18n/da.ts
packages/browser-wallet/src/popup/pages/TermsAndConditions/i18n/en.ts
packages/browser-wallet/src/popup/shell/Routes.tsx
packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
packages/browser-wallet/src/popup/store/settings.ts
packages/browser-wallet/src/popup/store/utils.ts
packages/browser-wallet/src/popup/styles/_components.scss
packages/browser-wallet/src/shared/constants/url.ts
packages/browser-wallet/src/shared/storage/access.ts
packages/browser-wallet/src/shared/storage/types.ts
packages/browser-wallet/src/shared/utils/network-helpers.ts

Ensure users accepts updated terms and conditions.
- Made a page after login that appears if a new terms and conditions is detected.
- Check terms and conditions on startup.

Make user accept the terms/conditions again, when the site changes

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/package.json

prepare publishing of new helpers version.

Bump helpers version + update changelog

---

examples/voting/package.json
examples/voting/src/Wallet.js
yarn.lock

Update voting example dependencies

Update voting example dependencies

---

yarn.lock

Fix merge yarn.lock error on CI

---

packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
packages/browser-wallet/src/popup/store/transactions.ts

Change transaction status instead of removing them

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/shared/TokenDetails/TokenDetails.scss
packages/browser-wallet/src/popup/shared/TokenDetails/TokenDetails.tsx

We want the NFT image to be displayed at the top of the NFT details page.

Re-arrange NFT details

---

examples/two-step-transfer/index.html
packages/browser-wallet-api/package.json
packages/browser-wallet-api/src/util.ts
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/SendTransaction/i18n/da.ts
packages/browser-wallet/src/popup/pages/SendTransaction/i18n/en.ts
packages/browser-wallet/src/popup/shared/TransactionReceipt/TransactionReceipt.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayRegisterData.tsx
packages/browser-wallet/src/popup/shared/i18n/da.ts
packages/browser-wallet/src/popup/shared/i18n/en.ts
packages/browser-wallet/src/popup/shared/utils/transaction-helpers.ts
packages/browser-wallet/src/popup/styles/util/_text.scss
yarn.lock

Fix sending register data transaction through wallet-api (and improve the display slightly)

Support sending register data transactions

---

examples/two-step-transfer/index.html
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/page-layouts/ExternalRequestLayout/ExternalRequestLayout.tsx
packages/browser-wallet/src/popup/page-layouts/MainLayout/Header/Header.scss
packages/browser-wallet/src/popup/page-layouts/MainLayout/MainLayout.scss
packages/browser-wallet/src/popup/page-layouts/MainLayout/MainLayout.tsx
packages/browser-wallet/src/popup/page-layouts/MainLayout/i18n/da.ts
packages/browser-wallet/src/popup/page-layouts/MainLayout/i18n/en.ts
packages/browser-wallet/src/popup/pages/ExternalAddTokens/ExternalAddTokens.tsx
packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.scss
packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.tsx
packages/browser-wallet/src/popup/pages/IdProofRequest/IdProofRequest.scss
packages/browser-wallet/src/popup/pages/IdProofRequest/IdProofRequest.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
packages/browser-wallet/src/popup/store/identity.ts
packages/browser-wallet/src/popup/styles/util/_flex.scss
packages/browser-wallet/src/popup/styles/util/_icons.scss
yarn.lock

Various UI alignments for ID proof view.
- Aligned external request layout header
- Show account/identity included in message payload instead of selected in external request layout
- Improve loading view when generating proof
- Removed statement line separator

Id2 view alignments

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/About/About.tsx
packages/browser-wallet/src/popup/pages/Account/AccountSettings/AccountSettings.scss
packages/browser-wallet/src/popup/pages/Account/AccountSettings/AccountSettings.tsx
packages/browser-wallet/src/popup/pages/Account/AccountSettings/AccountStatement.tsx
packages/browser-wallet/src/popup/pages/Account/AccountSettings/routes.ts
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/pages/TermsAndConditions/AcceptTerms.tsx
packages/browser-wallet/src/popup/shared/Button/Button.scss
packages/browser-wallet/src/popup/shared/ExternalLink/ExternalLink.tsx
packages/browser-wallet/src/shared/constants/url.ts

Add account statement page linking to ccdscan under account settings.

Export account statement

---

packages/browser-wallet/src/background/index.ts
packages/browser-wallet/src/background/window-management.ts

Test that there is a popup before blocking a new.

Fix blocking popups if the background script times out

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.scss

ID statement card were missing a background color. This adds that.

add bg to statement card

---

packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts

Fix errors in text on Id Proof popup

---

packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.tsx
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts
packages/browser-wallet/src/popup/shared/ExternalLink/ExternalLink.tsx
packages/browser-wallet/src/shared/constants/url.ts

Add documentation links to zkp modals

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/background/index.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.tsx
packages/browser-wallet/src/popup/pages/NetworkSettings/NetworkSettings.tsx
packages/browser-wallet/src/popup/pages/Setup/ChooseNetwork.tsx
packages/browser-wallet/src/popup/pages/TermsAndConditions/AcceptTerms.tsx
packages/browser-wallet/src/popup/shell/Root.tsx
packages/browser-wallet/src/popup/store/settings.ts
packages/browser-wallet/src/shared/constants/networkConfiguration.ts
packages/browser-wallet/src/shared/storage/types.ts
packages/browser-wallet/src/shared/utils/network-helpers.ts

Use wallet-proxy for terms and conditions.
- Changed how to check for new terms and conditions.
- Moved networkConfigurations into a contant file.
- Fixed a bug where id request popup threw a react error into the log.

Use wallet proxy for terms and conditions version

---

packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/utils.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts

Change when date of birth statements are interpreted as age. (+ Fixed singleton age display)

Fix id proof age checker and statement.lower to age calculation

---

packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.tsx
packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/utils.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/IdProofRequest.tsx
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts
packages/browser-wallet/src/popup/pages/TermsAndConditions/TermsAndConditions.scss
packages/browser-wallet/src/popup/shared/ExternalLink/ExternalLink.scss
packages/browser-wallet/src/popup/shared/ExternalLink/ExternalLink.tsx
packages/browser-wallet/src/popup/styles/_components.scss

Fixes a number of bugs for displaying ID statements:
- Text changes to statement information modal (clicking the "?" or "!" icon in the statement card header)
- Displaying countries in readable manner for reveal statements
- Correct text for range proofs (also with respect to inclusive/exclusive bounds)
- Always show the full range of a range statement in the description text (small text at the bottom of the statement card)

Various bugfixes

---

examples/wCCD/README.md
examples/wCCD/package.json
examples/wCCD/src/Root.tsx

close #210 
Add project version to the wCCD example 

Add project version to wCCD example

---

examples/two-step-transfer/package.json
examples/wCCD/package.json
packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api/package.json
packages/browser-wallet-api/src/wallet-api.ts
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
yarn.lock

Bump versions
- Fixed a bug where the add token didn't work when using the correct types.

Bump version to 9.4.0 + bump SDK version + fix wallet-api bug

---

packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts

Fix popup text/spacing

---

packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/utils.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts

Fix off-by-one error on upper to age calculation + text.

Fix off-by-one error on upper to age calculation

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/da.ts
packages/browser-wallet/src/popup/pages/IdProofRequest/i18n/en.ts
packages/browser-wallet/src/popup/shared/i18n/en.ts

Remove absolute trust + bump version.

Bump 0.9.5 + text changes

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/README.md
packages/browser-wallet-api-helpers/src/wallet-api-types.ts

Fix copy-paste error in README.

Fix copy-paste error in `addCIS2Tokens` description

---

examples/wCCD/src/wallet/BrowserWallet.ts
examples/wCCD/src/wallet/WalletConnect.ts
examples/wCCD/src/wallet/WalletConnection.ts
packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/README.md
packages/browser-wallet-api-helpers/src/wallet-api-types.ts
packages/browser-wallet-api/src/wallet-api.ts
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/SendCcd/ConfirmTransfer.tsx
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
packages/browser-wallet/src/popup/pages/SendTransaction/util.ts
packages/browser-wallet/src/popup/shared/TransactionReceipt/DisplayParameters.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/TransactionReceipt.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayInitContract.tsx
packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayUpdateContract.tsx
packages/browser-wallet/src/shared/utils/token-helpers.ts
packages/browser-wallet/src/shared/utils/types.ts

Fix some small errors.
- Change naming of contract init/update in transaction log.
- Unwrap message status wrapper in addCIS2Tokens.
- Add section for requestIdProofs in api-helpers readme.

Small fixes

---

examples/eSealing/Jenkinsfile

Fix build of the eSealing example dapp
Docker repo needs to be all lowercase

Docker repo should be all lowercase

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/package.json
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/Account/ManageTokens/ManageTokens.tsx
packages/browser-wallet/src/popup/pages/Account/ManageTokens/TokenList.tsx
packages/browser-wallet/src/popup/pages/Account/ManageTokens/state.ts
packages/browser-wallet/src/popup/pages/Account/ManageTokens/utils.ts
packages/browser-wallet/src/popup/pages/ExternalAddTokens/ExternalAddTokens.tsx
packages/browser-wallet/src/shared/storage/types.ts
packages/browser-wallet/src/shared/utils/token-helpers.ts
packages/browser-wallet/tsconfig.json

Fixes https://github.com/Concordium/concordium-browser-wallet/issues/252
- Fix deserialization.
- validate content against checksum, if present.

Fix token metadata url parsing with checksum

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/shared/utils/token-helpers.ts

Fix bug in last bugfix.
Fixed double extraction of response body, which caused an error.

Bump version + Fix double extraction of response body

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/package.json
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/AddAccount/i18n/da.ts
packages/browser-wallet/src/popup/pages/AddAccount/i18n/en.ts

Get ready to build version 1.0.0
- bumped versions.
- updated README.
- updated text for identities that has reached account limit.

Prepare for version 1.0.0

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionDetails.tsx
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionLog.scss

Improve readability of transaction events.
- Show events as a list instead of a concatinated string.

Improve readability of transaction events

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/Tokens/ManageTokens/ChooseContract.tsx

Clear the contract index input.
- The contract details form now has an empty default.
- The contract index input field is now autofocused.

Cis2 search keyword

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/Amount.tsx

Do not prefill stake amount with minimum amount
Do not default stake amount to minimum for non-bakers

Do not prefill stake amount with minimum amount

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Change title while registering a baker to "Register Baker" to align with mobile wallets.
Changed the title

Change title when registering a baker

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/background/recovery.ts
packages/browser-wallet/src/shared/storage/types.ts

Fix identities not being recovered 
Check identity indices where there is a rejected identity, and update/replace it if one is found.

Fix identities are not recovered if there is a rejected in place

---

packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api/package.json
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/Keys.tsx
packages/browser-wallet/src/popup/shared/utils/baking-helpers.ts
yarn.lock

Fix the bakerKey export, so that it can actually be used to run a node as a baker.
- Fix bakerKey export.
- Update web-sdk version.

Fix bakerKey export

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionDetails.tsx

Fix an error thrown by React due to missing keys in a list.
- Use event as the key for each event in the list.

Missing key transaction details

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Fix issues in baking and delegation text.
- Updated texts.

Fix issues in text.

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionMessage.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/RemoveBaking.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/RemoveDelegation.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/RemoveCarousel.tsx
packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
packages/browser-wallet/src/popup/shared/BlockChainParametersProvider.tsx
packages/browser-wallet/src/popup/shared/i18n/da.ts
packages/browser-wallet/src/popup/shared/i18n/en.ts

- Added popups before stopping baking/delegation.
- Added a hook for blockchain parameters that only returns the parameters if they are version 1.  

Add popups before stopping baking/delegation

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/Amount.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/MetadataUrl.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Earn.scss
packages/browser-wallet/src/popup/shared/i18n/da.ts
packages/browser-wallet/src/popup/shared/i18n/en.ts
packages/browser-wallet/src/shared/constants/baking.ts
packages/browser-wallet/src/shared/utils/energy-helpers.ts

Fix `configureBaker` crashing when registering
- display transaction fee when choosing amount for `configueBaker`.
- use max possible cost for validation when registering.

Fix configureBaker crashing when registering

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/utils.ts
packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/ConfigureDelegationFlow.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/utils.ts
packages/browser-wallet/src/popup/pages/Account/Earn/utils.ts
packages/browser-wallet/src/shared/utils/energy-helpers.ts

Have consistent display between delegation/baking
- Display the expected cost while choosing amount in configureDelegation.
- Don't use max possible cost for validation of delegation cost.

Display cost when choosing amount for configureDelegation + fix cost calculation

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/background/recovery.ts

Fix bug that causes empty recovery to end in error state.
Fix broken if statement

Fix empty recovery causes error

---

examples/eSealing/README.md
examples/nft-minting/README.md
examples/piggybank/README.md
examples/two-step-transfer/README.md
examples/voting/README.md
examples/wCCD/README.md
packages/browser-wallet/README.md

Fixes documentation to address #311 

Fixed documentation

---

examples/wCCD/CHANGELOG.md

It would be good to have a changeLog for the wCCD example. We intend to develop the example further with e.g. indexer data so it would be good to keep track of changes.

Add changeLog

---

packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api/package.json
packages/browser-wallet-api/src/wallet-api.ts
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionMessage.tsx
packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionPopup.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/RemoveBaking.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/RemoveDelegation.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Earn.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/utils.ts
packages/browser-wallet/src/popup/shared/BlockChainParametersProvider.tsx
packages/browser-wallet/src/popup/shared/utils/transaction-helpers.ts
yarn.lock

Ensure the wallet works with the new protocol version 6. 
- Updated SDK
- Remove usage of `isChainParametersV1` to denote "not ChainParametersV0".

Support P6

---

examples/voting/CHANGELOG.md
examples/voting/Jenkinsfile
examples/voting/package.json

Add jenkins file to voting

---

packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.stories.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.tsx
packages/browser-wallet/src/shared/storage/types.ts

Update types to match changes to schema and credential.
- Updated type definitions.

Update schema and credential types

---

packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.stories.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialList.tsx
packages/browser-wallet/src/popup/store/verifiable-credential.ts

Fix an issue where external data was fetched multiple times for no reason.
- Made the verifiable credentials atom into an `AsyncWrapper` to correctly handle the `loading` state.
- Fixed a type issue in a storybook story.

Fix dependency array bug

---

packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.stories.tsx

Fix errors that occurred after merging.

Fix faulty merge

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialDetails.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/da.ts
packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/en.ts

Display issuer contract index (subindex) under details.

Add contract address to verifiableCredentialDetails

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts

Fix validation of schema when downloaded.
- Updated the JSON schema used for validation to match the actual type.

Update verifiable credential schema JSON schema

---

packages/browser-wallet/src/popup/pages/Account/i18n/da.ts

Fix danish delegate update text

---

packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
packages/browser-wallet/src/shared/constants/logging.ts
packages/browser-wallet/src/shared/storage/update.ts
packages/browser-wallet/src/shared/utils/log-helpers.ts

Missed these changes in the previous PR.

Refactoring according to review

---

packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
packages/browser-wallet/src/popup/pages/Allowlist/Allowlist.scss
packages/browser-wallet/src/popup/shared/PopupMenu/PopupMenu.scss
packages/browser-wallet/src/popup/shared/Topbar/Topbar.scss
packages/browser-wallet/src/popup/styles/config/_colors.scss
packages/browser-wallet/src/popup/styles/elements/_base.scss

Enhance the UI.
- Removed margin on add web3 ID credential page.
- Made allowlist header readable in dark mode.
- Made the popup menu closer to the Figma drawings. In particular it also works better in dark mode now.

Remove bad margin from buttons

---

packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/VerifiableCredentialBackup.scss
packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/VerifiableCredentialImport.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/i18n/da.ts
packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/i18n/en.ts
packages/browser-wallet/src/popup/shared/Form/FileInput/FileInput.tsx
packages/browser-wallet/src/popup/shared/Form/FileInput/index.ts
packages/browser-wallet/src/popup/shared/Form/Form.scss

Add a nicer import experience.

Drag and drop

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/da.ts
packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/en.ts
packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts

Stop re-use of verifiable credential keys if they are already in the credential registry.
- Checks the registry contract whether a credential key has already been used or not.

Find correct next index for verifiable credentials

---

packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api/package.json
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/background/web3Id.ts
packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/VerifiableCredentialImport.tsx
packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/utils.ts
packages/browser-wallet/src/shared/storage/types.ts
yarn.lock

- Fix the export of timestamp credentials.
- Add validation of proof request parameters in statements.

Fix export

---

packages/browser-wallet/src/popup/styles-new/config/_typography.scss

Remove the button style causes tokens to look weird.

Remove new button style that is only changes the weight and line height

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/Web3ProofRequest/AccountStatement.tsx
packages/browser-wallet/src/popup/pages/Web3ProofRequest/VerifiableCredentialStatement.tsx
packages/browser-wallet/src/popup/pages/Web3ProofRequest/Web3ProofRequest.tsx
packages/browser-wallet/src/popup/pages/Web3ProofRequest/utils.ts

_Describe the purpose of the pull request, link to issue describing the problem, etc.

Fix selector resetting

---

packages/browser-wallet-api-helpers/src/wallet-api-types.ts

If the merge base is wrong, please let me know.

Aligned signature of method in wallet api interface with implementation

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/package.json

Ready wallet-api-helpers for release.

Bump version of wallet-api-helpers

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/package.json

Had to bump to 2.8.0 to be able to publish as we can't publish over an existing version (even if it has a tag).

Bump version to 2.8.0

---

.github/workflows/build-lint-test.yml
examples/eSealing/package.json
examples/nft-minting/package.json
examples/piggybank/package.json
examples/voting/package.json
examples/wCCD/package.json
package.json
packages/browser-wallet-api-helpers/package.json
packages/browser-wallet-api-helpers/src/index.ts
packages/browser-wallet-api/package.json
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
packages/browser-wallet/src/popup/shared/Form/Form.tsx
packages/browser-wallet/src/popup/shared/Form/common/utils.tsx
packages/browser-wallet/src/shared/utils/types.ts
packages/browser-wallet/test/wallet-api.test.ts
tsconfig.json
yarn.lock

Resolve to published ES module by default, aligning with the direction of our other published libraries.

Resolve to ESM by default

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/pages/Account/AccountTransactionFlow/AccountTransactionFlow.scss
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/CommissionField.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/Commissions.tsx
packages/browser-wallet/src/popup/pages/Account/Earn/Baking/utils.ts
packages/browser-wallet/src/popup/pages/Account/Earn/Earn.scss
packages/browser-wallet/src/popup/shared/Form/Form.scss
packages/browser-wallet/src/popup/shared/Form/InlineInput/InlineInput.tsx
packages/browser-wallet/src/popup/shared/Form/InlineNumber/InlineNumber.tsx
packages/browser-wallet/src/popup/shared/Form/InlineNumber/index.ts
packages/browser-wallet/src/popup/shared/Form/Slider/Slider.tsx
packages/browser-wallet/src/popup/shared/Form/Slider/index.ts
packages/browser-wallet/src/popup/shared/utils/baking-helpers.ts
packages/browser-wallet/src/popup/styles/_components.scss
yarn.lock

Enable changing commission rates, instead of being forced to use the minimum rate.
- Add sliders
- Adjustments to commission rates page.

Add Sliders for commissionFields

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Bump version + update changelog.

bump wallet version to 1.1.10

---

packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Improve wording / fix wording issues.
- Updated texts.

Fix some tokenomics renaming

---

packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
packages/browser-wallet/src/popup/pages/Account/i18n/en.ts

Fix wording issues.
- A number of issues in text has been fixed.

Adjustments to wording

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare for release build for testing.
- Bumped version to 1.3.1.

Bump version

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
yarn.lock

Fix the crash when inputting big numbers in update stake flow.
- Updated common helpers.
- Bumped version.

Handle big numbers when updating stake

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/constants/routes.ts
packages/browser-wallet/src/popup/pages/Settings/Settings.tsx
packages/browser-wallet/src/popup/pages/Settings/i18n/da.ts
packages/browser-wallet/src/popup/pages/Settings/i18n/en.ts
packages/browser-wallet/src/popup/pages/ViewSeedPhrase/ViewSeedPhrase.scss
packages/browser-wallet/src/popup/pages/ViewSeedPhrase/ViewSeedPhrase.tsx
packages/browser-wallet/src/popup/pages/ViewSeedPhrase/i18n/da.ts
packages/browser-wallet/src/popup/pages/ViewSeedPhrase/i18n/en.ts
packages/browser-wallet/src/popup/pages/ViewSeedPhrase/index.ts
packages/browser-wallet/src/popup/shell/Routes.tsx
packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
packages/browser-wallet/src/popup/styles/_components.scss

Display seed phrase.
Added page for showing seed phrase.

Add page in settings to show seedPhrase

---

packages/browser-wallet-message-hub/src/message.ts
packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/background/recovery.ts
packages/browser-wallet/src/popup/pages/Recovery/Recovery.scss
packages/browser-wallet/src/popup/pages/Recovery/RecoveryMain.tsx
packages/browser-wallet/src/popup/pages/Recovery/i18n/da.ts
packages/browser-wallet/src/popup/pages/Recovery/i18n/en.ts
packages/browser-wallet/src/popup/store/identity.ts

Allow aborting recovery when there are no identities

Allow aborting recovery when there are no identities

---

packages/browser-wallet-api-helpers/CHANGELOG.md
packages/browser-wallet-api-helpers/package.json

Prepare a release of browser-wallet-api-helpers 3.0.1

Prepare a release of browser-wallet-api-helpers 3.0.1

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx

Allow all accounts to be created.

Allow creating an account with the max index

---

README.md
examples/wCCD/Dockerfile
examples/wCCD/package.json
packages/browser-wallet/README.md

Make the README's more useful.

Improve README's

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/src/background/index.ts

Fix #441  
Add onUpdated listener to inject script.

Add additional listener for inject script

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Bump version 1.5.0

---

.github/workflows/build-lint-test.yml
examples/eSealing/Dockerfile
examples/voting/Dockerfile
examples/wCCD/Dockerfile

Ensure the docker files are not "silently broken". :upside_down_face:

Check that docker files can be built in CI

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare for release of browser wallet 1.5.1

Prepare browser wallet for release of 1.5.1

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare for release of browser wallet 1.5.2

Prepare browser wallet for release of 1.5.2

---

examples/wCCD/CHANGELOG.md
examples/wCCD/package.json
examples/wCCD/src/wCCD.tsx

Prepare wCCD example for release of 4.1.3

Prepare wCCD example for release of 4.1.3

---

packages/browser-wallet/CHANGELOG.md

Update CHANGELOG.md
Added sign CIS3 message feature to Changelog. Previously was missed in changelog.

[BRO-13] Payload decoding in the browser wallet of the CIS3 standard

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
yarn.lock

Update `@concordium/web-sdk` to version `7.5.1` fixing the issue during account creation 
Closes #483

Release 1.6.1

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare for release of browser wallet 1.7.0

Prepare browser wallet for release of 1.7.0

---

packages/browser-wallet/src/popup/pages/Web3ProofRequest/Web3ProofRequest.scss
packages/browser-wallet/src/popup/popupX/constants/routes.ts
packages/browser-wallet/src/popup/popupX/page-layouts/MainLayout/Header/Header.scss
packages/browser-wallet/src/popup/popupX/page-layouts/MainLayout/Header/components/MenuTiles.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Baker/Intro/BakerIntro.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Intro/DelegatorIntro.scss
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Intro/DelegatorIntro.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/EarningRewards.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/i18n/en.ts
packages/browser-wallet/src/popup/popupX/pages/SeedPhrase/SeedPhrase.scss
packages/browser-wallet/src/popup/popupX/shared/Button/Button.scss
packages/browser-wallet/src/popup/popupX/shared/Button/Button.tsx
packages/browser-wallet/src/popup/popupX/shared/Carousel/Carousel.scss
packages/browser-wallet/src/popup/popupX/shared/Carousel/Carousel.tsx
packages/browser-wallet/src/popup/popupX/shell/Routes.tsx
packages/browser-wallet/src/popup/popupX/styles/_base.scss
packages/browser-wallet/src/popup/styles-new/config/_colors.scss
packages/browser-wallet/src/popup/styles-new/config/_typography.scss

Ran `stylelint ./**/*.scss` which is why there are some seemingly random style changes as well.
Closes #535
- Added `Button.Text` to represent text as a clickable button with no styling
- Base styling for `ul` and `ol` corresponding to design

UI update/setup delegation intro

---

packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Baker/Intro/BakerIntro.scss
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Baker/Intro/BakerIntro.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/i18n/en.ts

Move baker intro text to translations

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare for release of browser wallet 1.7.1

Prepare browser wallet for release of 1.7.1

---

packages/browser-wallet/src/popup/popupX/shared/FullscreenNotice/FullscreenNotice.scss
packages/browser-wallet/src/popup/popupX/shared/FullscreenNotice/FullscreenNotice.stories.tsx
packages/browser-wallet/src/popup/popupX/shared/FullscreenNotice/FullscreenNotice.tsx
packages/browser-wallet/src/popup/popupX/shared/FullscreenNotice/index.ts
packages/browser-wallet/src/popup/popupX/styles/_elements.scss
packages/browser-wallet/src/popup/shared/Modal/Modal.stories.tsx

The component can be viewed in storybook under `X/shared/FullscreenNotice`

Component for showing a fullscreen notice/warning/message to the user

---

packages/browser-wallet/src/popup/popupX/constants/routes.ts
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Result/DelegationResult.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Status.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/i18n/en.ts
packages/browser-wallet/src/popup/popupX/shell/Routes.tsx
packages/browser-wallet/src/shared/utils/time-helpers.ts

UI update/remove delegation

---

packages/browser-wallet/src/popup/popupX/constants/routes.ts
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Result/ValidationResult.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Status/Status.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/TransactionFlow.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Update.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/i18n/en.ts
packages/browser-wallet/src/popup/popupX/shell/Routes.tsx

Add flows for updating an active validator

---

packages/browser-wallet/src/popup/popupX/pages/MainPage/MainPage.tsx
packages/browser-wallet/src/popup/popupX/pages/MainPage/i18n/en.ts

Right after completing account creation, the account will have status of pending.
This PR extends the home page to show information for pending accounts.

Main/home page pending accounts.

---

packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Stake/DelegatorStake.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/TransactionFlow.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Stake/ValidatorStake.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/TransactionFlow.tsx
packages/browser-wallet/src/popup/popupX/styles/_base.scss

Alignments with design with regards to text

UI update/text color fix

---

packages/browser-wallet/src/popup/popupX/pages/EarningRewards/AccountCooldowns/AccountCooldowns.scss
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/AccountCooldowns/AccountCooldowns.stories.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/AccountCooldowns/AccountCooldowns.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Result/DelegationResult.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Status/Status.scss
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Status/Status.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Status/index.ts
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/EarningRewards.scss
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/EarningRewards.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Status/Status.tsx
packages/browser-wallet/src/popup/popupX/pages/EarningRewards/i18n/en.ts
packages/browser-wallet/src/popup/popupX/styles/_elements.scss
packages/browser-wallet/src/popup/shared/utils/transaction-helpers.ts

Ensure that it is always possible as a user to view the release schedule of your inactive stake by adding it to the main screen of earning rewards.

UI update/stake cooldown visibility

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json
packages/browser-wallet/src/popup/popupX/page-layouts/MainLayout/Header/components/AccountSelector.tsx
packages/browser-wallet/src/popup/popupX/pages/prompts/ConnectAccount/ConnectAccount.tsx

Fix black screen on new UI
Error in console 'Cannot read properties of undefined (reading 'toLowerCase')'
Fix Credentials with some fields undefined

BW hotfix 2.0.1

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare BW for new release
Updated package version and Changelog

BW 2.1.2 release

---

.github/workflows/release.yml

Ubuntu-20.04 is deprecated
Update to 24.04

Release workflow versions update

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare BW for new release
Updated package version and Changelog

BW 2.2.0 release

---

.github/workflows/build-lint-test.yml
packages/browser-wallet/jest.config.ts

Fix Build, Lint, Test workflow steps
https://github.com/Concordium/concordium-browser-wallet/actions/runs/14617512879
Updated ubuntu and github-actions to new versions

Update workflow actions and ubuntu versions

---

package.json
packages/browser-wallet-api-helpers/package.json
yarn.lock

Packages update

---

packages/browser-wallet/src/popup/popupX/pages/MainPage/MainPage.tsx

Added Buy button to pending account screen. So it is aligned with main page.
<table>
<tr>
<td><img width="385" alt="Screenshot 2025-07-07 at 12 59 05" src="https://github.com/user-attachments/assets/d5e72369-de68-4f78-8897-4ae3582b209c" /></td>
<td><img width="383" alt="Screenshot 2025-07-07 at 12 58 16" src="https://github.com/user-attachments/assets/b06c01e7-7bf5-42de-a773-24fff4c3ea13" /></td>
</tr>
</table>

[No-Task] Update pending account screen

---

packages/browser-wallet/CHANGELOG.md
packages/browser-wallet/package.json

Prepare BW for new release
Updated package version and Changelog

BW 2.6.0 release
