- packages/browser-wallet/src/popup/pages/Account/Account.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/store/settings.ts
It is annoying that you can't reset connections without reinstalling the wallet, so I added a temporary button to do it :upside_down_face: 
Added the button
> Add button to reset connections

- packages/browser-wallet/src/popup/pages/About/About.scss
- packages/browser-wallet/src/popup/pages/About/About.tsx
- packages/browser-wallet/src/popup/pages/About/i18n/da.ts
- packages/browser-wallet/src/popup/pages/About/i18n/en.ts
- packages/browser-wallet/src/popup/pages/About/index.ts
- packages/browser-wallet/src/popup/pages/Settings/Settings.scss
- packages/browser-wallet/src/popup/shell/Routes.tsx
- packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
- packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
- packages/browser-wallet/src/popup/styles/_components.scss
Add the about page. Note that the terms and conditions and license notices are not linked yet, as they are separate tasks.
- Updated the CSS for the Settings page to have a background color instead of the background image.
- Updated the about page to contain the version, the support email and relevant links to documentation, the support forum and the main Concordium website.
> Add the about page

- examples/piggybank/src/Root.tsx
- examples/two-step-transfer/index.html
- packages/browser-wallet-api-helpers/CHANGELOG.md
- packages/browser-wallet-api-helpers/README.md
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
- packages/browser-wallet-message-hub/src/handlers.ts
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/AccountSettings.scss
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/ConnectedSites.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/pages/ConnectionRequest/ConnectionRequest.tsx
Allow users to manually connect to a site. Broadcast a disconnect event when removing a connection and an accountChanged event when adding a new connection, but only to the given site.
- Added new disconnect event to WalletApi. Emitted to the disconnected tab.
- Added option to manually connect the currently open tab's website to the wallet.
- An accountChanged event is emitted when manually connecting to a site, but only to that site.
- Connected site whitelisting now uses the `origin` field on the URL instead of the full URL which was too restrictive.
> Add ability to manually add connection to a site

- packages/browser-wallet/src/popup/pages/Account/Account.scss
- packages/browser-wallet/src/popup/pages/Account/Account.tsx
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/AccountSettings.scss
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/ConnectedSites.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/shared/utils/tabs.ts
Add a status box to let the user know if the currently open tab is connected to the wallet.
- Added a status box with connected / not connected information. Pressing the box navigates to the connected sites for the currently selected account.
- Fixed UI scrolling issue when user had many sites connected.
> Add site connected status box to account page

- examples/piggybank/src/Root.tsx
- examples/piggybank/src/Version0.tsx
- examples/piggybank/src/Version1.tsx
- examples/piggybank/src/utils.ts
- packages/browser-wallet-api-helpers/CHANGELOG.md
- packages/browser-wallet-api-helpers/README.md
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet-message-hub/src/message.ts
- packages/browser-wallet/src/background/index.ts
Add `getSelectedAccount` to the wallet-api, and make the piggybank example use it.
Added `getSelectedAccount` to the wallet api + handling it in the background script.
Refactor piggyBank, and use `getSelectedAccount` instead of doing unprompted connects.
> getSelectedAccount

- packages/browser-wallet-message-hub/package.json
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/constants/routes.ts
- packages/browser-wallet/src/popup/page-layouts/MainLayout/MainLayout.tsx
- packages/browser-wallet/src/popup/pages/Login/Login.scss
- packages/browser-wallet/src/popup/pages/Login/Login.tsx
- packages/browser-wallet/src/popup/pages/Login/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Login/i18n/en.ts
- packages/browser-wallet/src/popup/pages/Setup/RecoveryPhrase.tsx
- packages/browser-wallet/src/popup/shell/Routes.tsx
- packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
- packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
- packages/browser-wallet/src/popup/store/settings.ts
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/popup/styles/_components.scss
- packages/browser-wallet/src/shared/storage/access.ts
- packages/browser-wallet/src/shared/storage/types.ts
- yarn.lock
Add a login screen where the user can input their password for decrypting the seed phrase. The passcode is saved in chrome.storage.session, and is reset if the browser is closed.
- Added a login screen.
- Force navigate to login screen if no passcode has been provided yet.
> Require passcode

- packages/browser-wallet-api-helpers/README.md
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/popup/pages/ConnectionRequest/ConnectionRequest.tsx
- packages/browser-wallet/src/popup/pages/Login/Login.tsx
- packages/browser-wallet/src/popup/shell/Routes.tsx
Ensure that the wallet API is locked down if the wallet is locked.
- A connect request to a locked wallet prompts the user to unlock, and then to connect.
- The JSON-RPC interface will reject if the wallet is locked.
- Sign transaction and sign message will reject if the wallet is locked. An improvement we can do later is to specifically return the reason, right now it's not possible to see if it was the user rejecting or the wallet was locked.
> Reject when locked

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/page-layouts/MainLayout/AccountList/AccountList.tsx
When a user searched for accounts it would give what looked like faulty results as it searched all fields on a credential. It is now restricted to only searching on the address. When we add naming to accounts that field should be searched.
- Use searchable key when searching for accounts, set to the account address.
> Only search address field when searching accounts

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/index.ts
Fix an issue where the wallet did not listen for the status of identities and accounts on installation.
- Run startup listener on `onInstalled` event.
> Listen for identity and account status onInstalled

- packages/browser-wallet/src/popup/pages/Account/AccountSettings/ExportPrivateKey.tsx
Ensure that the user has to re-enter the password for the wallet if switching account while exporting private keys.
- Stop showing the private key if the selected account address changes.
> Re-lock export of private key on account change

- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/shared/AccountInfoListenerContext/AccountInfoListenerContext.tsx
- packages/browser-wallet/src/popup/shared/account-info-listener.ts
- yarn.lock
Fix crashing account view
(also merges 0.5.0 bump into main)
Use out internal json stringify/parse functions for accountInfo to not corrupt bigints.
> Ensure that bigints in accountInfo are not converted to numbers

- packages/browser-wallet/src/background/credential-deployment.ts
- packages/browser-wallet/src/background/identity-issuance.ts
- packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
- packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceEnd.tsx
- packages/browser-wallet/src/popup/shared/AccountInfoListenerContext/AccountInfoListenerContext.tsx
- packages/browser-wallet/src/popup/store/account.ts
- packages/browser-wallet/src/popup/store/identity.ts
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/shared/storage/access.ts
Ensure that the checks that prevents duplicate account/identity creation is set in the background script.
Move the update of the checks from popup to background.
Set atomsWithStorage to have sync as default.
> Update checks for creating identity and account in background script

- packages/browser-wallet/src/popup/pages/Account/Account.tsx
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/ConnectedSites.tsx
- packages/browser-wallet/src/popup/pages/Account/ConnectedBox.tsx
- packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
- packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
- packages/browser-wallet/src/popup/shared/utils/tabs.ts
Ensured that getCurrentOpenTabUrl doesn't throw an error.
Now getCurrentOpenTabUrl return undefined if there is no tab.
+ added a hook for gettting the current url.
> Fix getCurrentOpenTabUrl throwing error

- packages/browser-wallet/package.json
- packages/browser-wallet/src/background/recovery.ts
- packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
- packages/browser-wallet/src/popup/shared/utils/account-helpers.ts
- packages/browser-wallet/src/shared/utils/number-helpers.ts
- packages/browser-wallet/test/account-helpers.test.ts
Align some stuff regarding recovery and account creation with the mobile wallet.
Increase maxEmpty gap to 20.
Use next available credNumber instead of highest + 1.
Check gaps in accounts during recovery.
> Update recovery/account creation to align with mw

- packages/browser-wallet/src/popup/shared/AccountInfoListenerContext/AccountInfoListenerContext.tsx
Fix an issue where the account info from a wrong account was used to display a balance.
- Reset account info on genesis change or address change.
> Fix issue with wrong account info

- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
- packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceStart.tsx
- packages/browser-wallet/src/popup/pages/Recovery/RecoveryMain.tsx
- packages/browser-wallet/src/popup/shared/utils/account-helpers.ts
- packages/browser-wallet/src/popup/shared/utils/seedPhrase-helpers.ts
- packages/browser-wallet/src/popup/store/settings.ts
Fix recovery from settings so that it fails gracefully, instead of exploding the entire wallet. (I also think the normal recovery would explode everything if that also failed)
Ensure that we don't navigate from the RecoveryMain component before the seedPhrase loading atom is done loading.
> Fix recovery from settings crashing when there is an error

- packages/browser-wallet/manifest.json
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/AccountSettings.scss
- packages/browser-wallet/src/popup/pages/Account/AccountSettings/ExportPrivateKey.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/shared/utils/account-helpers.ts
Add a button in export private key to export as a file.
- Added that button.
- Created usePublicKey and useHdWallet hooks.
- Fixed textarea in exportPrivateKey not being readOnly. 
> Add button to export private key as file

- packages/browser-wallet-api-helpers/README.md
The relative link does not work on the published version https://www.npmjs.com/package/@concordium/browser-wallet-api-helpers
Fix link and typos.
> Fix a link and some typos

- packages/browser-wallet/src/background/index.ts
Fix issue when trying to connect to an empty wallet (a wallet without any accounts).
- Check if there is a selected account before checking if the wallet is locked, when doing a connection request.
> Reject connection request if no selected account

- packages/browser-wallet/src/background/confirmation.ts
- packages/browser-wallet/src/background/credential-deployment.ts
- packages/browser-wallet/src/background/identity-issuance.ts
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/background/recovery.ts
- packages/browser-wallet/src/background/update.ts
Ensure identityaccount creation doesnt not fail to confirm due to `undefined.signal`
- Remove abortController.
- status monitors are now given the current network's genesisHash and terminate the loop if the current network has a different genesisHash.
- change update function to take the genesisHash as a parameter instead of loading it themselves. (To avoid loading the wrong network if it was changed while checking the status)
> Fix undefined signal

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/ConnectionRequest/ConnectionRequest.tsx
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/shared/storage/access.ts
Store connected sites per network to avoid cross pollution in the case of multiple testnet networks (in the future).
- Make stored connected sites indexed by genesis hash.
> Connected sites per network

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
Fix an issue in account creation where another identity than the one chosen was shown.
- Fix the identity index in `ChooseIdentity.tsx`. As the index is the index in the total list, and not just of confirmed identities, we have to ensure that we process all identities when building the list.
> Wrong selected identity when having failed identities

- examples/wCCD/src/utils.ts
- packages/browser-wallet-api-helpers/CHANGELOG.md
- packages/browser-wallet-api-helpers/package.json
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
Fix misleading types in the API, which lead users to believe they could supply the parameters for a smart contract as a buffer in the payload, when this is ignored, because we want them not serialized, so we can display them.
- Change the typing
- update changelog
- bump api-helpers version
> Remove parameters from smart contract payload types in api

- packages/browser-wallet/src/popup/pages/Account/AccountActions/AccountActions.scss
- packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
- packages/browser-wallet/src/popup/shared/account-info-listener.ts
- packages/browser-wallet/src/popup/store/transactions.ts
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/shared/storage/access.ts
Discovered some issues when setting up a new account on a freshly added network:
- pending transactions were not network specific
- pending transaction amount displayed wrong
- network specific atoms didn't update when changing network
- Refactor pending transactions atom to set value through atom when possible
- Refresh atoms on network change
- Make `TransactionListElement` render pending transactions properly in terms of amount and cost both for sending and receiving accounts
> Pending transactions indexed by network

- packages/browser-wallet-api-helpers/package.json
- packages/browser-wallet-api/package.json
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
- packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceStart.tsx
- packages/browser-wallet/src/popup/pages/Recovery/RecoveryMain.tsx
- packages/browser-wallet/src/popup/shared/AccountInfoListenerContext/AccountInfoListenerContext.tsx
- packages/browser-wallet/src/popup/shared/account-info-listener.ts
- packages/browser-wallet/src/popup/store/settings.ts
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/shared/storage/access.ts
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/utils/network-helpers.ts
- yarn.lock
Use cookies for communication with JSON-RPC.
- jsonRpcClientAtom now uses/updates a cookie.
- Use jsonRpcClientAtom where possible.
- Update Web-SDK.
> Adjust to cookie-supporting JSON-RPC client

- packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionLog.scss
- packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
- packages/browser-wallet/src/popup/store/transactions.ts
Discovered some small things pertaining to how pending transactions are shown.
- undefined sender of pending ccd-drop transaction
- correct color of pending transaction icon (previous didn't work in dark mode, and didn't align with the color of finalized transaction)
> Improve pending transactions

- packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
- packages/browser-wallet/src/popup/shared/utils/transaction-history-types.ts
- packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
Transactions that were rejected because of malformed body weren't shown in the browser wallet, hiding the full picture of expenses for an account for the user. This enables the transaction type to be shown in the transaction list
- Remove filter on transactions endpoint.
> Show malformed transactions in transaction history.

- packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
- packages/browser-wallet/src/popup/pages/Account/SendCcd/SendCcd.scss
It was hard to see that you could actually select a token from the create transfer page. This adds an indication that you can, while also aligning with the implementation in the mobile wallet.
- Add search icon to select token field.
> Add indication that tokens can be selected from send page

- packages/browser-wallet/src/popup/pages/Recovery/Recovery.scss
- packages/browser-wallet/src/popup/pages/Recovery/RecoveryFinish.tsx
Add an exit button when recovery has failed, so that you are not "stuck".
> Add exit button for recovery finish screen, if not a spawned window

- packages/browser-wallet/src/popup/pages/Account/ManageTokens/utils.ts
- packages/browser-wallet/src/popup/pages/ExternalAddTokens/ExternalAddTokens.tsx
- packages/browser-wallet/src/popup/shared/TokenBalance.tsx
- packages/browser-wallet/src/popup/shared/i18n/da.ts
- packages/browser-wallet/src/popup/shared/i18n/en.ts
- packages/browser-wallet/src/popup/store/token.ts
- packages/browser-wallet/src/shared/utils/token-helpers.ts
- Filter tokens with failing `balanceOf` in Manage page 
- Show error when `balanceOf` fails 
- Show no balance instead of nothing in token list/detail if `balanceOf` fails.
> Improve handling of bad balanceOf on tokens

- packages/browser-wallet-api/src/wallet-api.ts
Support the differently name fields from older SDK versions for sendTransaction.
> Improve sendTransaction backwards compatibility

- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/shared/i18n/da.ts
- packages/browser-wallet/src/popup/shared/i18n/en.ts
- packages/browser-wallet/src/shared/utils/token-helpers.ts
I'm not sure who thought this was a good idea, but it turns out, using the i18n outside react, it uses the shared file.
> Fix CIS0 and CIS2 error labels when choosing contract

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/SendTransaction/util.ts
Fix blank prompt when requesting an `initContract` transaction with parameters.
Fixed the field name used for serializing the parameter. 
> Fix init contract parameter parsing

- packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
Block user from sending transfers to accounts that have not been created.
- Reworked recipient validation function in transfer
- Removed todo for issue that has already been fixed
> Validate that recipient exists on transfer

- packages/browser-wallet/src/popup/shared/Img.tsx
Tokens with no image now displays failed placeholder image instead loading. 
Changes in Img component behaviour.
> Img now defaults to failed image if no src is given

- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/popup/pages/TermsAndConditions/AcceptTerms.tsx
- packages/browser-wallet/src/shared/utils/network-helpers.ts
To remove the burden of keeping the wallet-proxy versions in sync (or risk extra prompts), we will only use the mainnet one.
> Always use mainnet proxy for terms and conditions

- examples/wCCD/src/Root.tsx
- examples/wCCD/src/WalletConnectorTypeButton.tsx
- examples/wCCD/src/wCCD.tsx
- examples/wCCD/src/wallet/BrowserWallet.ts
- examples/wCCD/src/wallet/WalletConnect.ts
- examples/wCCD/src/wallet/WalletConnection.ts
- examples/wCCD/src/wallet/WithWalletConnection.tsx
Display error messages in the application instead of logging them to console or showing alert popups. This adds a bunch of error fields to the various components' state.
Error messages got a pass and the connection logic was migrated from the app component into the `WithWalletConnection` library component.
This improves the UX and solves the following issues:
- Browser Wallet:
- Clean up event handlers when "disconnecting" (i.e. discarding) the connector. This avoids interference between reconnects.
- Show error message when browser wallet isn't available.
- WalletConnect:
- Disconnect is now detected properly.
- Ensure that we no longer get stuck in "waiting for user" state when the modal is closed without connecting.
- RPC errors are improved and displayed in the UI. This makes it as …
> wCCD: Improve error handling

- examples/wCCD/src/utils.ts
- examples/wCCD/src/wCCD.tsx
Make it possible to specify receiving address of wrap/unwrap. This is to accomodate the need for testing transactions made from smart contract udpates, initiated by other accounts than than the receiving address itself.
This change should be deployed to the public wccd testnet app, so critique/change requests are welcome.
- Add field to specify receiving address.
> Wccd receiver address

- packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionList.tsx
- packages/browser-wallet/src/popup/shared/AccountInfoListenerContext/AccountInfoListenerContext.tsx
- packages/browser-wallet/src/popup/store/transactions.ts
Make it possible to refresh account info from atom. Also update account info when pending transactions are confirmed.
> Make account info atom refreshable

- .github/workflows/build-lint-test.yml
Ensure that changes in library functions that didn't involve dependency changes invalidate the CI's dependency cache.
Include hash of `package.json` in the cache key.
Also included a dummy value for force invalidating the cache and parameterize node version.
> CI: Include hash of package.json in cache key

- examples/eSealing/package.json
- examples/eSealing/src/eSealing.tsx
The label around the file input covered a lot of elements below the component, such that e.g. clicking on the computed file hash opened the file dialog.
Also, once a file hash computation returned an error, this error would never be reset even if it was successful afterwards (can trigger error on Ubuntu by selecting a text file, editing the file, then computing the hash). Fixed by resetting the error on success.
The change is nowhere near as complex as GitHub makes it look. A proper viewer will reveal that most of it is reindentation.
> eSealing: Fix label and error resetting

- packages/browser-wallet/src/popup/pages/AddAccount/AddAccount.scss
- packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
- packages/browser-wallet/src/popup/pages/AddAccount/i18n/da.ts
- packages/browser-wallet/src/popup/pages/AddAccount/i18n/en.ts
- packages/browser-wallet/src/popup/shared/IdCard/IdCard.scss
- packages/browser-wallet/src/popup/shared/IdCard/IdCard.tsx
- packages/browser-wallet/src/shared/utils/identity-helpers.ts
Block user from trying (and failing) to create accounts on identities which has already reached the limit.
- Disable identity cards in list when creating new account, if limit has been reached. (and display a message)
- IdCard now have pointer cursor when clickable
> Handle account limit when picking identity to create a new account with

- examples/two-step-transfer/index.html
- examples/two-step-transfer/package.json
- packages/browser-wallet-api-helpers/CHANGELOG.md
- packages/browser-wallet-api-helpers/README.md
- packages/browser-wallet-api-helpers/package.json
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
- packages/browser-wallet-api/package.json
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/background/credential-deployment.ts
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.scss
- packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
- packages/browser-wallet/src/popup/pages/SignMessage/i18n/da.ts
- packages/browser-wallet/src/popup/pages/SignMessage/i18n/en.ts
- yarn.lock
Extend sign_message wallet API to support signing arbitrary data.
- Extend wallet-api so signMessage can receive an object with data/schema instead of only a string.
- Fix signMessage error response, so it doesn't always say "signing was rejected".
- Bump web-sdk version.
- Add an example to the two-step-transfer that uses the new format.
> Add support for SignMessageObject as input to signMessage

- examples/two-step-transfer/index.html
- packages/browser-wallet-api/src/constants.ts
- packages/browser-wallet-api/src/util.ts
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/jest.config.ts
- packages/browser-wallet/package.json
- packages/browser-wallet/src/background/confirmation.ts
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/popup/pages/Account/DisplayAddress/DisplayAddress.tsx
- packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
- packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
- packages/browser-wallet/src/popup/shared/TransactionReceipt/TransactionReceipt.tsx
- packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayGenericPayload.tsx
- packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayInitContract.tsx
- packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplaySimpleTransfer.tsx
- packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayUpdateContract.tsx
- packages/browser-wallet/src/popup/store/token.ts
- packages/browser-wallet/src/shared/utils/payload-helpers.ts
- packages/browser-wallet/src/shared/utils/types.ts
- yarn.lock
- Fix crashes when opening token raw Metadata (and other modals) 
- Fix bad parameters from dApps crashing the wallet (the request is now rejected instead)
Use updated wallet-common-helpers that support both commonJS (for tests) and ES Modules (for the wallet itself)
- I recently changed that library to use commonJS modules instead of ES, to make the tests run, but it turns out that references to react-dom then stopped working. Now it uses compiles both versions and we use ES modules in the wallet build and commonJS when running the tests now.
To fix the bad parameters crashing the wallet, I've added a check in the background script that rejects the transaction, if we are unable to serialize the parameters.
- I had to move some things around, because the parse function we use for …
> Fix opening portals causing blank screen 

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/TransactionLog/TransactionElement.tsx
- packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
Fix bug that caused transaction history to not load when account has a `updateCredentialsKeys` transaction.
- Fix expected key from wallet proxy for `updateCredentialsKeys`.
- Change name for `updateCredentialsKeys` in list to `Account keys update`.
> Fix mismatch in string identifier for UpdateCredentialsKeys from wallet-proxy

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/shared/utils/baking-helpers.ts
Do not display extra decimals on commissions
Set minimum decimals to 0 on commissions.
> Do not display extra decimals on commissions

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/recovery.ts
Fix duplicate identity names after recovery 
Identity nextId is no longer incremented by existing identities, it is now initialized to after the existing amount
> Fix duplicate identity names after recovery 

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/Tokens/Tokens.tsx
Fix double unit on CCD in the token overview.
Removed CCD unit display after CCD amount in token overview.  
> Remove double unit for CCD in token overview

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/background/confirmation.ts
- packages/browser-wallet/src/background/credential-deployment.ts
- packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
- packages/browser-wallet/src/popup/pages/AddAccount/i18n/da.ts
- packages/browser-wallet/src/popup/pages/AddAccount/i18n/en.ts
- packages/browser-wallet/src/shared/utils/types.ts
- yarn.lock
Fix bad behaviour, which has recently worsened, when creating an existing account.
- Add existing account when trying to recreate it.
- Add missing await in credential-deployment.
- Fix `monitorCredentialStatus` not halting when "transaction not found".
> Fix behaviour when attempting to creating existing account

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/Amount.tsx
- packages/browser-wallet/src/popup/pages/Account/Earn/Baking/utils.ts
Fix an issue where updating the baker stake for a baker would make the wallet crash.
- Allow no changes to the baker settings when calculating the cost.
- Use current baker settings as fallback when calculating cost instead of random default values.
> Baker crash

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/Earn/Baking/FlowPages/Amount.tsx
Fix incorrect cost used to validate baker stake.
Convert energy cost to CCD before using it to validate baker stake.
> Use CCD cost instead of energy cost to validateBakerStake

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/ConfigureDelegationFlow.tsx
Fix delegation target always defaulting to baker, even if current target was a passive delegation.
Fixed the default to passive delegation, when account is already using passive delegation.
> Fix delegation target always defaulting to baker

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionMessage.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
Update transaction messages to all include cooldownPeriod + align the texts between baking and delegation.
- Changed transactionMessage text.
- Fixed reduceStake messages being shown instead of remove message when stake = 0.
> Update transaction messages

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/ConfirmTransfer.tsx
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionMessage.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/shared/i18n/da.ts
- packages/browser-wallet/src/popup/shared/i18n/en.ts
Add popups that appear after sending configure baker/delegation transactions.
> Add popups when updating baking/delegation

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/utils.ts
Fix delegation target being updated to passive delegation when the user did not choose to update it.
Change loose equality to strict to differentiate between null and undefined.
> Fix target delegation being updated incorrectly

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/ConfirmTransfer.tsx
Display errors from node in a nicer way.
- display error message instead of stringifying the error + decode uri encoding.
> Improve how confirmTransfer displays errors

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/ConfirmTransfer.tsx
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionMessage.tsx
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionPopup.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
Align with mobile wallet on "finish transaction" screen.
- Refactor `transactionMessage` into two components.
- Stop displaying `transactionMessage` after the transaction has been sent.
- Display "Transaction Submitted!" after it was submitted.
> Remove transactionMessage after transaction has been submitted

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/SendTransaction/i18n/da.ts
- packages/browser-wallet/src/popup/pages/SendTransaction/i18n/en.ts
- packages/browser-wallet/src/popup/shared/TransactionReceipt/TransactionReceipt.scss
- packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayDeployModule.tsx
Fixes for `deployModule` display.
Bumped version to 1.0.6.
In deploy module display:
- Change `module hash` to `module reference`.
- Add copy button for module reference.
> Deploy module fixes

- packages/browser-wallet-api/src/gRPC-transport.ts
- packages/browser-wallet/CHANGELOG.md
Before, the URL was not actually immediately used, instead the client would always use the previous call's URL, which on the first call is undefined. It also meant that after changing network, the first call would still be directed to the old network. 
This should fix that.
Apply base settings immediately before performing the actual call.
> Fix grpc client first call failing

- packages/browser-wallet-api-helpers/CHANGELOG.md
- packages/browser-wallet-api-helpers/package.json
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
This makes it possible to construct an object adhering to the `SchemaWithContext` type from the JS SDK, to make it easier for a user to directly use the SDK to call the wallet API.
> Wallet api types/lax schematype

- examples/wCCD/Jenkinsfile
Docker images are now built for a specific network, added network to image tag.
> Add network to docker image tag

- examples/voting/CHANGELOG.md
- examples/voting/package.json
- examples/voting/src/CreateElectionPage.js
- examples/voting/src/Footer.js
- examples/voting/src/HomePage.js
- examples/voting/src/Results.js
- examples/voting/src/VotePage.js
All hosted front ends should have a way to find the source code easily. Either through a link to an associated tutorial (that contains links to the source code) or if no tutorial exists through a link to the source code.
- Add link to tutorial.
- Add `ChangeLog`.
- Add `version` to front end.
> Add link to voting tutorial

- packages/browser-wallet-api-helpers/src/util.ts
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
- packages/browser-wallet/test/wallet-api.test.ts
Relax transaction type parameter in the `wallet-api`, so numbers can be given directly and tsc doesn't complain if a different version of the enum is used.
> Relax AccountTransactionType in wallet-api

- examples/eSealing/CHANGELOG.md
- examples/eSealing/package.json
- examples/eSealing/src/Root.tsx
- examples/eSealing/src/constants.ts
- examples/eSealing/src/eSealing.tsx
- examples/eSealing/src/utils.ts
- yarn.lock
- JSON-RPC is deprecated and will be eventually removed from all our libraries. This PR migrates the eSealing dApp.
- Replace using jsonRPC with gRPC
> Change from json-rpc to grpc

- .github/workflows/build-lint-test.yml
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.stories.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialStatus.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/da.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/en.ts
- packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
- packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Adjust to changes to metadata format and fix some bugs.
- Adjusted `background_color` to `backgroundColor`.
- Fixed an issue where new updates from on chain would delete existing metadata.
- Added credential status translations.
- Run workflow on PR towards a feature branch (and pushes to it).
> Background color and update fixes

- examples/voting/CHANGELOG.md
- examples/voting/package.json
- examples/voting/src/CreateElectionPage.js
- examples/voting/src/Wallet.js
- yarn.lock
- JSON-RPC is deprecated and will be eventually removed from all our libraries. This PR migrates the voting dApp.
-  Replace using jsonRPC with gRPC
> Replace json-rpc with grpc in voting dApp

- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredential.scss
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialDetails.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialList.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/da.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/en.ts
- packages/browser-wallet/src/popup/shared/PopupMenu/PopupMenu.tsx
- packages/browser-wallet/src/popup/shared/Topbar/Topbar.tsx
- packages/browser-wallet/src/shared/utils/time-helpers.ts
Add a button for showing "extra details" about a credential, i.e. non-attribute information.
- Added details button to more menu for credentials in the details view.
- Adjusted popup menu component to support what's needed.
> Extra details

- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredential.scss
- packages/browser-wallet/src/popup/styles/elements/_base.scss
Stop images from breaking list view.
- Adjustments to the verifiable credential list view with new margins, taking the scrollbar gutter into consideration.
- Set a fixed pixel size for the scrollbar-width.
CLA acceptance
> Adjust scrollbar to improve list view

- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet/src/background/web3Id.ts
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/VerifiableCredentialStatement.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/Web3ProofRequest.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/utils.ts
Enable proofs with number attributes.
- Handle number attributes in proofs
- Don't crash on non-existant attributes (might be moot due to the next point)
- Now filter credential that don't have the attribute, even if its nonMembership.
> Fix proofs with number attributes

- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredential.scss
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialDetails.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/da.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/en.ts
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Display issuer metadata to the user (if available).
- Now fetching the issuer metadata and showing on the extra details page for a verifiable credential. Note that all the fields in the metadata are optional, so there might not be anything to show.
> Display issuer metadata in credential details page

- packages/browser-wallet/src/popup/pages/VerifiableCredentialBackup/VerifiableCredentialImport.tsx
Avoid crashing when importing credentials with schemas that are not already in storage.
Wait for schemas and metadata to be saved before displaying imported credentials.
> Fix importing web3Id credentials without the schemas already in storage

- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialDetails.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialList.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/VerifiableCredentialStatement.tsx
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Add localization for verifiable credentials.
- Fetch the localization files and apply them when displaying a verifiable credential.
It is missing some validation when getting the localization file, where we want to ensure that all the keys from the schema are present. We will do that soonTM.
> Add initial support for localization

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/Web3ProofRequest.tsx
Stop crashing when the wallet contains verifiable credentials that are not on chain yet.
Catch when getting status, like we do in the hook.
> Fix proof blank screen, when wallet contains vc that is not on chain

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/utils.ts
Fix that sometimes the account credential issuer / identityProviderIndex was incorrect.
Fix lookup of identity, which just chose the first identity always.
> Fix faulty identity selector

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialDetails.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/popup/store/verifiable-credential.ts
- packages/browser-wallet/src/shared/storage/access.ts
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Display pending verifiable credentials.
- Add session storage for verifiable credential metadata.
- Use session stored metadata if credentialEntry is missing.
- Catch some errors in VC hooks.
> Display pending verifiable credentials

- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/da.ts
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/en.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/shared/storage/access.ts
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/storage/update.ts
- packages/browser-wallet/src/shared/utils/log-helpers.ts
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Add logging of failure events for easier debugging.
- Added logging entry to `chrome.storage`. It will currently store the most recent 100 events.
- For the development build errors are also logged to `console`.
- Added logging to the Web3 ID error scenarios I could find where we wanted it to be logged.
> Web3 ID logging

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialStatus.tsx
Use the correct translation for `NotActivated`.
- Use the correct translation.
> Use correct text for not activated status

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/en.ts
Improve schema validation when adding a Web3 ID credential. 
- Now checks that the credential to be added does not contain any attribute not mentioned in the schema.
- Added a missing CHANGELOG entry from another PR.
> Prevent adding a credential with attributes not listed in schema

- examples/add-example-Web3Id/package.json
- examples/eSealing/package.json
- examples/nft-minting/package.json
- examples/piggybank/package.json
- examples/two-step-transfer/package.json
- examples/voting/package.json
- examples/wCCD/package.json
- packages/browser-wallet-api-helpers/package.json
- packages/browser-wallet-api/package.json
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/background/web3Id.ts
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/VerifiableCredentialStatement.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/utils.ts
- packages/browser-wallet/src/popup/shared/utils/account-helpers.ts
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
- yarn.lock
> Update web sdk and fix related TODOS

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/utils/log-helpers.ts
Handle credential metadata being changed (in the contract) to something invalid.
- Save the metadata URL that is received when adding the credential, and use this if the credential entry (or the temp metadata url) does not match anything in storage.
Note that we should also be updating the fallback URL everytime we get new valid metadata, but we can add that in the future.
> Add credential metadata fallback

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/web3Id.ts
Enable verification of ID statements like we had for ID2.0.
- Now also runs `verifyIdStatement`.
> Verify id statements when checking for valid proofs

- packages/browser-wallet-api/src/util.ts
- packages/browser-wallet/CHANGELOG.md
Prevent an issuer from trying to add an invalid date to the wallet.
- Throw an error in the JSON replacer if the Date is not valid.
> Throw error in replacer if date is invalid

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/page-layouts/MainLayout/i18n/da.ts
- packages/browser-wallet/src/popup/page-layouts/MainLayout/i18n/en.ts
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/da.ts
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/i18n/en.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.stories.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialCard.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialDetails.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialHooks.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialList.tsx
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/da.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/i18n/en.ts
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/VerifiableCredentialStatement.tsx
- packages/browser-wallet/src/shared/storage/types.ts
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Improve the handling in the wallet when a schema changes. This is both for cases where the schema is changed to something invalid, but also just the case of the schema changing to a new hosting URL. The wallet will now, instead of crashing, show if a schema is not valid for the credential. If the schema URL changes to an invalid schema, then the wallet will fallback and use the schema received when first adding the credential. This is then shown to the user along with a message that something is wrong.
- Update the credential schema hook to use the credential schema URL from the contract, and only use the fallback URL from the credential if there is no match on the contract URL.
- When displaying a credential we are now more lenient and accept schemas that are missing keys for attributes. …
> Improve handling of changes to schema

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/web3Id.ts
Validate that add credential requests do not contain invalid attributes.
- Added validation when receiving a request to add a credential.
> Validate attributes based on their types

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
Fix an issuse where credential schemas did not update correctly.
- Use the `URL` where we got the schema from as the key when updating the local storage.
> Use real URL as key for schema updates

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/CredentialSelector.tsx
- packages/browser-wallet/src/popup/pages/Web3ProofRequest/Web3ProofRequest.scss
- packages/browser-wallet/src/popup/shared/Modal/Modal.tsx
_Describe the purpose of the pull request, link to issue describing the problem, etc.
> Improve credential selector

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/web3Id.ts
- packages/browser-wallet/src/popup/pages/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/shared/utils/verifiable-credential-helpers.ts
- packages/browser-wallet/test/verifiable-credential-helpers.test.ts
Fix issue where credentials with integer values in their schema could not be added.
> Allow bigints as type integer

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
- packages/browser-wallet/src/popup/pages/SignMessage/i18n/da.ts
- packages/browser-wallet/src/popup/pages/SignMessage/i18n/en.ts
Fix Request message was not rendered correctly.
-   Fix Sign message's rendered view displaying 'a' when deserialization failed.
-   Sign message deserialization failing with new `deserializeTypeValue`.
> Fix sign message rendered message display

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/shared/TransactionReceipt/displayPayload/DisplayInitContract.tsx
Correctly render the max contract execution energy for init contract transactions.
- Use the internal value of the execution energy when displaying it.
> Fix rendering of max contract execution energy

- examples/add-example-Web3Id/package.json
- examples/eSealing/package.json
- examples/nft-minting/package.json
- examples/piggybank/package.json
- examples/two-step-transfer/package.json
- examples/voting/package.json
- examples/wCCD/package.json
- packages/browser-wallet-api/package.json
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- yarn.lock
Update the used web-sdk to a version that contains a fix to init contract serialization. Also updates the wallet-common-helpers to a version that uses the same web-sdk version. A mismatch between the browser wallet and the wallet-common-helpers leads to bugs.
- Updated to web-sdk 7.0.3
> Use web-sdk 7.0.3 only

- examples/piggybank/src/utils.ts
- examples/two-step-transfer/index.html
- examples/two-step-transfer/package.json
- packages/browser-wallet-api/src/compatibility.ts
- packages/browser-wallet-api/test/compatibility.test.ts
- packages/browser-wallet/CHANGELOG.md
Fix potential errors caused by version mismatch in SDK version with dApps.
- Remove usage of instanceOf when sanitizing wallet-api inputs.
- Use AccountAddress in piggybank.
> Remove usage of instanceof when sanitizing wallet-api inputs

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
Fix some wording.
- Updated some text.
> Fix bake/produce wording

- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
Fix text when updating validator stake.
> Update validator stake text fixes

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/background/update.ts
- packages/browser-wallet/src/popup/store/utils.ts
- packages/browser-wallet/src/shared/constants/migrations.ts
- packages/browser-wallet/src/shared/constants/token-metadata.ts
- packages/browser-wallet/src/shared/storage/access.ts
- packages/browser-wallet/src/shared/storage/types.ts
Show EuroE in wallet
- Added migration to add EuroE to all existing accounts.
- Now EuroE is added by default to new/restored accounts.
> Add EuroE token by default

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/Account/Earn/Earn.tsx
- yarn.lock
Restore missing date for when stake changes take effect.
- Stop using deprecated (and erroneous) `isRewardStatusV1`.
- Update common wallet helpers to a version that doesn't use `isRewardStatusV1`.
> Fix missing date for when stake changes take effect

- packages/browser-wallet-api/package.json
- packages/browser-wallet-api/src/compatibility.ts
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet/CHANGELOG.md
- yarn.lock
Some websites throw errors because our inject script tries to load wasm. It doesn't need any wasm though, so this makes sure it doesn't try to load it anyway. (By using the new web-sdk version)
> Ensure inject script does not load wasm.

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/Tokens/ManageTokens/ChooseContract.tsx
- packages/browser-wallet/src/popup/pages/Account/Tokens/ManageTokens/state.ts
- packages/browser-wallet/src/popup/pages/Account/Tokens/ManageTokens/utils.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
- packages/browser-wallet/src/popup/store/token.ts
- packages/browser-wallet/src/shared/utils/contract-helpers.ts
- packages/browser-wallet/src/shared/utils/token-helpers.ts
Make CIS-2 token lookup more lenient
- Redo `getTokens` so that metadataURL and balances are fetched individually.
- Log errors from token lookup, don't show them in UI.
- Don't fail "Choose Contract" unless all tokens are missing either metadata or balance.
- `fetchTokensConfigure` now keeps looking until 1 valid token is found (/or all tokens in the contract have been checked)
> Make CIS-2 token lookup more lenient

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/shared/utils/transaction-helpers.ts
Fix "Changing restaking options not possible for validators below minimum stake"
- During validation, handle case of below minimum, but amount has not changed.
> Allow restaking when below minimum stake

- packages/browser-wallet-api-helpers/CHANGELOG.md
- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
- packages/browser-wallet-api/package.json
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
- packages/browser-wallet/src/popup/shared/TransactionReceipt/DisplayParameters.tsx
- packages/browser-wallet/src/shared/utils/payload-helpers.ts
- packages/browser-wallet/src/shared/utils/types.ts
- yarn.lock
Closes #420.
- The injected script will now send the smart contract parameters _stringified_ using `json-bigint`, which is then parsed in the extension when parsing the payload. This is all internal and should not result in any breaking changes.
- The type `SmartContractParameters` is extended with `bigint`.
> Fix: Error when using bigint in smart contract parameters

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/store/settings.ts
Fix a bug where recovery from the wallet settings menu would use a list of identity providers from the wrong network.
- Reset the identity provider atom when updating the network.
> Wrong identity providers

- packages/browser-wallet-api/package.json
- packages/browser-wallet-api/src/wallet-api.ts
- yarn.lock
Re-expose legacy GRPC client, this time from `@concordium/common-sdk`.
I verified that this does not trigger requesting any WASM.
> Expose legacy GRPC client from common-sdk

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
Fix an issue where the wrong identity was used for creating an account if the wallet contained failed identities.
- Gather all identities to be able to set the correct identity storage index, so that on the following page the correct identity is shown as the selected one.
Note that this is just a quickfix. In general the fact that this is controlled by a global value in storage is bad, and ideally we would refactor it.
> Fix ChooseIdentity component using wrong identity index

- .github/workflows/release.yml
Build the prod build and the development build in a GitHub action. The files are just uploaded to GitHub for now but will ensure consist builds, and we can stop building releases locally. An additional step would be to publish the release to the Chrome extension store.
- GitHub action that builds and uploads the browser wallet for production and development.
> Add pipeline for building releases

- examples/add-example-Web3Id/package.json
- examples/eSealing/package.json
- examples/nft-minting/package.json
- examples/piggybank/package.json
- examples/two-step-transfer/package.json
- examples/voting/package.json
- examples/wCCD/package.json
- packages/browser-wallet-api/package.json
- packages/browser-wallet-api/src/compatibility.ts
- packages/browser-wallet-api/src/util.ts
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet-api/test/compatibility.test.ts
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/DisplayStatement.tsx
- packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/utils.ts
- packages/browser-wallet/src/shared/utils/payload-helpers.ts
- packages/browser-wallet/src/shared/utils/proof-helpers.ts
- yarn.lock
Implements the changes described in https://github.com/Concordium/concordium-node-sdk-js/issues/307.
> Use new transaction fromJSON and toJSON

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/pages/Account/SendCcd/CreateTransfer.tsx
- packages/browser-wallet/src/shared/utils/energy-helpers.ts
- packages/browser-wallet/src/shared/utils/token-helpers.ts
Fix the token transfer estimate not aligning with other wallets / wallet proxy.
- Use the transfer amount for token transfers, when calculating cost.
- Fix update payload size to contain the 1 byte that represent transaction type.
> Fix token transfer energy cost estimate

- packages/browser-wallet-message-hub/src/message.ts
- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/background/web3Id.ts
- packages/browser-wallet/src/popup/page-layouts/MainLayout/MainLayout.scss
- packages/browser-wallet/src/popup/pages/Account/Account.tsx
- packages/browser-wallet/src/popup/pages/IdentityIssuance/IdentityIssuanceEnd.tsx
- packages/browser-wallet/src/popup/pages/Settings/Settings.scss
- packages/browser-wallet/src/popup/pages/Settings/Settings.tsx
- packages/browser-wallet/src/popup/pages/Settings/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Settings/i18n/en.ts
- packages/browser-wallet/src/popup/pages/VerifiableCredential/VerifiableCredentialList.tsx
- packages/browser-wallet/src/popup/shared/window-helpers.ts
- packages/browser-wallet/src/popup/shell/Root.tsx
Add a button that opens the browser wallet in fullscreen mode (in a tab).
- Added button in settings that will open the wallet in a tab instead of the extension popup window.
- Adjusted the UI of the wallet to work better in the fullscreen mode (centered, some margins, hide some overflows of menus, hide the connected box, go to identities page on issuance end, fix issue with web3id import popup window).
> Fullscreen view

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/IdProofRequest/DisplayStatement/utils.ts
- packages/browser-wallet/test/id-proof-util.test.ts
Fix a bug in the check for EU country set.
- Invert the check to actually check if the set of countries is exactly the EU members.
> Fix bug in check for EU country set

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/index.ts
Closes #457 
This PR is a quick fix ensuring that the script is only injected when the tab is done loading, instead of the current solution which results in on every change to any of the tab information.
See documentation for [`tabs.onUpdated`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated).
- Remove the listener for messages from the content script to inject the script.
- Change the `tabs.onUpdated` listener to only inject when tab is done loading page.
> Fix issue with multiple injected scripts

- examples/eSealing/package.json
- examples/eSealing/vite.config.ts
- examples/voting/package.json
- examples/voting/vite.config.ts
- examples/wCCD/package.json
- examples/wCCD/src/wCCD.tsx
- examples/wCCD/vite.config.ts
- yarn.lock
It would be both good user experience to suggest to add the newly wrapped token to the user's wallet, as well as a good example to demonstrate this functionality in an example app to spread its visibility.
Created new button "Add Token to wallet" that calls addCIS2Tokens from browser-wallet-api-helpers
[Screencast from 27.03.24 12:13:57.webm](https://github.com/Concordium/concordium-browser-wallet/assets/164325149/9be05d17-2261-41fa-a2c4-4be82ff453e0)
> [BRO-9] Add addCIS2Tokens to the wCCD example

- packages/browser-wallet-api-helpers/src/wallet-api-types.ts
- packages/browser-wallet-api/src/wallet-api.ts
- packages/browser-wallet-message-hub/src/message.ts
- packages/browser-wallet/src/background/index.ts
- packages/browser-wallet/src/popup/constants/routes.ts
- packages/browser-wallet/src/popup/pages/SignCIS3Message/SignCIS3Message.scss
- packages/browser-wallet/src/popup/pages/SignCIS3Message/SignCIS3Message.tsx
- packages/browser-wallet/src/popup/pages/SignCIS3Message/i18n/da.ts
- packages/browser-wallet/src/popup/pages/SignCIS3Message/i18n/en.ts
- packages/browser-wallet/src/popup/pages/SignCIS3Message/index.ts
- packages/browser-wallet/src/popup/pages/SignMessage/SignMessage.tsx
- packages/browser-wallet/src/popup/shell/Routes.tsx
- packages/browser-wallet/src/popup/shell/i18n/locales/da.ts
- packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
- packages/browser-wallet/src/popup/styles/_components.scss
The browser wallet can also decode the payload field by looking up the parameter schema of the entry_point_name and using this schema to decode the payload. The payload is the input parameter that is sent to the entry_point_name.
Proposal on how to decode the payload for the CIS3 contract.
> [BRO-13] Payload decoding in the browser wallet of the CIS3 standard

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/background/identity-issuance.ts
When launching identity issuance, the browser wallet will send a request the ID provider and be redirected to the onboarding flow.
The browser wallet checks the redirected URL does not contain the `redirectUrl` which is later used for signalling the end of the flow, but there is no error handling for this case, so the wallet fails silently and is stuck on the page for generating the request.
One fix could be to produce an actual error, but this check seems arbitrary and provide no value, so instead I have removed it.
Also, it was hit by accident by an upcoming identity provider.
I have checked that this still works with every identity provider on testnet.
- Remove the check of the redirected identity issuance url.
> Remove check of redirectUri

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/DisplayAddress/DisplayAddress.scss
Padding for QR code background. In dark mode, QR code not blending with background.
Updated styles
> [BRO-15] Address of QR code difficult to scan in dark mode

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
- Use new wallet proxy endpoint with company ID providers
- Prepare release of 1.6.3
> Use new wallet-proxy endpoint and prepare release of 1.6.3

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/shared/utils/wallet-proxy.ts
We need yet another release to prepare the wallet for company ID providers on mainnet.
- Use the new wallet proxy endpoint which will include company ID providers (when available on mainnet).
> Prepare release of 1.6.4

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/pages/Account/ConfirmTransfer/TransactionMessage.tsx
- packages/browser-wallet/src/popup/pages/Account/i18n/da.ts
- packages/browser-wallet/src/popup/pages/Account/i18n/en.ts
> Update screens mentioning stake cooldown

- packages/browser-wallet/src/popup/popupX/constants/routes.ts
- packages/browser-wallet/src/popup/popupX/pages/Accounts/Accounts.tsx
- packages/browser-wallet/src/popup/popupX/pages/ConnectedSites/ConnectedSites.scss
- packages/browser-wallet/src/popup/popupX/pages/ConnectedSites/ConnectedSites.tsx
Use account data on connect sites page.
> Hook up Account connected sites page

- packages/browser-wallet/src/popup/popupX/constants/routes.ts
- packages/browser-wallet/src/popup/popupX/pages/Accounts/Accounts.tsx
- packages/browser-wallet/src/popup/popupX/pages/PrivateKey/PrivateKey.tsx
Change key export page to show the key for the account in the list and not the selected account.
- Add account to the path for the page.
- Have two empty lines during loading of the key to avoid UI jumping. This will have to be revised when responsive version is implemented.
> Key export for account in list

- packages/browser-wallet/src/popup/popupX/constants/routes.ts
- packages/browser-wallet/src/popup/popupX/pages/Accounts/Accounts.tsx
- packages/browser-wallet/src/popup/popupX/pages/IdCards/IdCards.scss
- packages/browser-wallet/src/popup/popupX/pages/IdCards/IdCards.tsx
- packages/browser-wallet/src/popup/popupX/pages/Onboarding/IdSubmitted.tsx
- packages/browser-wallet/src/popup/popupX/pages/Restore/RestoreResult.tsx
- packages/browser-wallet/src/popup/popupX/shared/EditableValue/EditableValue.scss
- packages/browser-wallet/src/popup/popupX/shared/EditableValue/EditableValue.tsx
- packages/browser-wallet/src/popup/popupX/shared/EditableValue/index.ts
- packages/browser-wallet/src/popup/popupX/shared/IdCard/IdCard.tsx
- packages/browser-wallet/src/popup/popupX/shared/i18n/en.ts
- packages/browser-wallet/src/popup/popupX/styles/_elements.scss
- packages/browser-wallet/src/wallet-common-helpers/utils/ccd.ts
Display actual identities in ID cards page
- Factor out `useEditableValue` for shared logic between account name and identity name editing.
> Hook up IdCards page with actual data

- packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Status.tsx
- packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Result/ValidationResult.tsx
- packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Validator/Status/Status.tsx
- packages/browser-wallet/src/popup/popupX/pages/EarningRewards/i18n/en.ts
- packages/browser-wallet/src/popup/popupX/pages/SubmittedTransaction/SubmittedTransaction.tsx
- packages/browser-wallet/src/popup/popupX/pages/SubmittedTransaction/i18n/en.ts
Fixes an issue where the the validator status screen would cause application to crash if a validator was removed. Also adds missing text to the submission progress screen for validator transactions.
> UI update/fix stop validation

- packages/browser-wallet/src/popup/popupX/constants/routes.ts
- packages/browser-wallet/src/popup/popupX/pages/Web3Id/Web3Id.scss
- packages/browser-wallet/src/popup/popupX/pages/Web3Id/Web3IdCredentials.tsx
- packages/browser-wallet/src/popup/popupX/pages/Web3Id/Web3IdDetails.tsx
- packages/browser-wallet/src/popup/popupX/pages/Web3Id/Web3IdImport.tsx
- packages/browser-wallet/src/popup/popupX/pages/Web3Id/i18n/en.ts
- packages/browser-wallet/src/popup/popupX/shared/Web3IdCard/Web3IdCard.scss
- packages/browser-wallet/src/popup/popupX/shared/Web3IdCard/Web3IdCard.stories.tsx
- packages/browser-wallet/src/popup/popupX/shared/Web3IdCard/Web3IdCard.tsx
- packages/browser-wallet/src/popup/popupX/shared/i18n/en.ts
- packages/browser-wallet/src/popup/popupX/shared/utils/verifiable-credentials.ts
- packages/browser-wallet/src/popup/popupX/shell/Routes.tsx
- packages/browser-wallet/src/popup/shared/Img.tsx
> UI update/web3id overview

- packages/browser-wallet/src/popup/popupX/constants/routes.ts
- packages/browser-wallet/src/popup/popupX/pages/prompts/AddWeb3IdCredential/AddWeb3IdCredential.scss
- packages/browser-wallet/src/popup/popupX/pages/prompts/AddWeb3IdCredential/AddWeb3IdCredential.tsx
- packages/browser-wallet/src/popup/popupX/pages/prompts/AddWeb3IdCredential/i18n/en.ts
- packages/browser-wallet/src/popup/popupX/shared/Form/FileInput/index.ts
- packages/browser-wallet/src/popup/popupX/shared/Web3IdCard/Web3IdCard.tsx
- packages/browser-wallet/src/popup/popupX/shell/Routes.tsx
- packages/browser-wallet/src/popup/popupX/styles/_elements.scss
- packages/browser-wallet/src/popup/shell/i18n/locales/en.ts
Wraps up managing web3 id credentials in the wallet.
> Add prompt for adding web3 ID credentials

- packages/browser-wallet/src/popup/shared/utils/transaction-helpers.ts
Fixes a bug where, in some cases, you could not submit staking transactions with stake in cooldown
> Use total account amount when checking available funds for staking

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/manifest.json
- packages/browser-wallet/package.json
Web extension is being rejected because of an unused `"downloads"` permission.
This PR removes it and prepares a release.
> Remove unused "downloads" permission

- packages/browser-wallet/src/popup/popupX/pages/SubmittedTransaction/SubmittedTransaction.tsx
- packages/browser-wallet/src/popup/popupX/pages/TransactionLog/TransactionDetails/TransactionDetails.scss
- packages/browser-wallet/src/popup/popupX/pages/TransactionLog/TransactionDetails/TransactionDetails.tsx
- packages/browser-wallet/src/popup/popupX/pages/TransactionLog/TransactionLog.tsx
- packages/browser-wallet/src/popup/shared/utils/transaction-history-types.ts
Enable linking directly to transaction details page
> UI update/tx details link

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/package.json
- packages/browser-wallet/src/popup/popupX/page-layouts/MainLayout/Header/components/AccountSelector.tsx
- packages/browser-wallet/src/popup/popupX/pages/Accounts/Accounts.tsx
- packages/browser-wallet/src/popup/popupX/pages/prompts/ConnectAccount/ConnectAccount.tsx
Fix Credentials with address undefined
filtered out credentials with address undefined
> BW hotfix 2.0.2

- .github/workflows/release.yml
Git-hub actions v2 is deprecated
Update to v4
Ubuntu-20.04 is deprecated
Update to 24.04
Details in 
Notice of upcoming releases and breaking changes for GitHub Actions
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
Version update
> Release workflow versions update

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/popupX/pages/EarningRewards/Delegator/Type/DelegationType.tsx
replace the existing link to match the one the mobiles
Updated delegation description help link from `node` list to `staking`
> Update Delegation Description help link

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/popupX/shell/Routes.tsx
Added a fix where the user was not able to do web3id age verification 
Updated handleWeb3IdProofResponse to handleAgeProofResponse
By submitting the contribution, I accept the terms and conditions of the
> CRE-463  BUG: Proof Explorer Fix

- packages/browser-wallet/CHANGELOG.md
- packages/browser-wallet/src/popup/popupX/pages/ConnectNetwork/ConnectNetwork.tsx
- packages/browser-wallet/src/popup/popupX/pages/ConnectNetwork/CustomConnectNetwork.tsx
- packages/browser-wallet/src/popup/popupX/pages/ConnectNetwork/i18n/en.ts
After successfully connecting to a network in the browser wallet, there is no confirmation message
Added connection message Toast
> [WAL-1252] Browser Wallet: No Success Confirmation Message
